services:
  backend:
    build:
      context: ./EldenRingApi
      dockerfile: Dockerfile
    ports:
      - "5035:5035"
    volumes:
      - ./EldenRingApi:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./elden-app
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
